package com.thievestrap

import android.content.Context

object Strings {

    fun get(context: Context, key: String): String {
        val lang = context.getSharedPreferences("tt_prefs", Context.MODE_PRIVATE)
            .getString("language", "en") ?: "en"
        return getStr(lang, key)
    }

    fun getStr(lang: String, key: String): String = when (lang) {
        "fr" -> FR[key] ?: EN[key] ?: key
        "ar" -> AR[key] ?: EN[key] ?: key
        else -> EN[key] ?: key
    }

    val EN = mapOf(
        // App
        "app_name" to "Thieves Trap",
        "arm" to "ARM",
        "disarm" to "DISARM",
        "armed" to "ARMED",
        "disarmed" to "DISARMED",
        "settings" to "Settings",
        "language" to "Language",
        "last_alert" to "Last alert",
        "never" to "Never",
        "not_set" to "Not set",
        "cancel" to "Cancel",
        "change" to "Change",
        "saved" to "Saved!",
        "back" to "Back",
        // PIN
        "enter_pin" to "Enter your PIN",
        "wrong_pin" to "Wrong PIN! Alert sent.",
        "disarm_title" to "Disarm Thieves Trap",
        "current_pin" to "Current PIN",
        "new_pin" to "New PIN (4–6 digits)",
        "change_pin" to "Change Security PIN",
        "pin_too_short" to "PIN must be at least 4 digits!",
        "pin_changed" to "PIN changed successfully!",
        // Setup
        "setup_title" to "First Setup",
        "setup_subtitle" to "Required before arming",
        "setup_done" to "START PROTECTING MY PHONE",
        "setup_complete" to "Setup complete! Phone is now protected.",
        "imei_required" to "IMEI is required! Dial *#06# to find it.",
        "contact_required" to "Emergency contact phone is required!",
        // Permissions
        "permissions_required" to "All permissions are required!",
        "no_contact" to "Enter a phone number in Settings first!",
        "admin_explanation" to "Thieves Trap needs admin access to protect your phone.",
        // Status
        "mode_theft" to "THEFT MODE — all alerts active",
        "mode_normal" to "Normal mode — monitoring password attempts",
        "theft_mode_on" to "Theft mode ACTIVATED",
        "theft_mode_off" to "Theft mode deactivated",
        // Premium
        "premium_required" to "Premium Required",
        "premium_message" to "This feature is available in the Full Protection plan.",
        "upgrade_now" to "Upgrade Now",
        "not_now" to "Not now",
        "premium_active" to "Full Protection Active",
        "free_version" to "Free Version",
        "revoke_license" to "Revoke License",
        "license_revoked" to "License revoked.",
        "license_activated" to "Full Protection unlocked!",
        "license_invalid" to "Invalid license key. Keys are device-specific.",
        "enter_key" to "Enter license key",
        "get_device_id" to "Get Device ID for purchase",
        // Settings sections
        "section_identity" to "DEVICE IDENTITY",
        "section_contacts" to "EMERGENCY CONTACTS",
        "section_theft_alerts" to "THEFT ALERTS",
        "section_grace" to "SMART GRACE PERIOD",
        "section_device_alerts" to "DEVICE STATUS ALERTS",
        "section_remote" to "REMOTE CONTROL",
        "section_language" to "LANGUAGE",
        "section_security" to "SECURITY",
        "section_info" to "APP INFO",
        // Settings labels
        "my_number" to "Your phone number",
        "imei_label" to "IMEI (dial *#06#)",
        "imei_hint" to "Open your phone dialer and dial *#06# — your IMEI appears immediately.",
        "contact1" to "Contact 1 (required)",
        "contact2" to "Contact 2",
        "contact2_locked" to "🔒 Contact 2 — Premium Only",
        "photo_email" to "Email to receive intruder photos",
        "photo_email_locked" to "🔒 Photo Email — Premium Only",
        "save_identity" to "Save Identity",
        "save_contacts" to "Save Contacts",
        "sms_failed_label" to "SMS on failed attempts",
        "sms_failed_sub" to "Always active",
        "selfie_label" to "Selfie on failed attempts",
        "selfie_sub" to "Photo saved locally + emailed (Premium)",
        "sim_change_label" to "SMS on SIM change",
        "sim_change_sub" to "🔒 Premium",
        "grace_toggle_label" to "Enable Smart Grace Period",
        "grace_toggle_sub" to "Wait before sending alert after wrong PIN",
        "grace_off_label" to "Smart Grace Period: OFF",
        "airplane_label" to "Airplane mode — 🔒 Premium",
        "shutdown_label" to "Shutdown / Reboot — 🔒 Premium",
        "silent_label" to "Silent mode change — 🔒 Premium",
        "charging_label" to "Charger connect / disconnect — 🔒 Premium",
        "ping_toggle_label" to "Auto location ping — 🔒 Premium",
        "ping_interval_label" to "Ping interval:",
        "threshold_label" to "Alert after N failed attempts:",
        "change_language" to "Change Language",
        "test_sms" to "Send Test SMS",
        "test_sent" to "Test SMS sent!",
        "reset_stats" to "Reset Statistics",
        "reset_done" to "Statistics reset!",
        "total_alerts" to "Total alerts",
        "revoke_key_btn" to "Revoke License Key",
        "select_language" to "Select Language",
        // Remote guide
        "remote_guide_title" to "Remote Control Guide",
        "remote_guide_sub" to "Send from ANY phone — no registration needed",
        "remote_how_title" to "HOW IT WORKS",
        "remote_how_en" to "These keywords are your remote commands. Send them from any phone to trigger actions on your stolen device. Open SMS on any other phone, type the command (e.g. WHERE), and send to your stolen phone number.",
        "remote_how_ar" to "هذه الكلمات المفتاحية هي اوامر التحكم عن بعد. ارسلها من اي هاتف لتفعيل الحماية على هاتفك المسروق.",
        "section_location" to "LOCATION COMMANDS",
        "section_device_info" to "DEVICE INFORMATION",
        "section_security_actions" to "SECURITY ACTIONS",
        "section_tracking" to "TRACKING",
        "section_control" to "CONTROL",
        // SMS messages
        "sms_armed" to "Thieves Trap activated. Phone is protected. Send HELP for commands.",
        "sms_unlock" to "Phone was successfully unlocked!",
        "sms_failed_attempts" to "WARNING: %d failed unlock attempts detected!",
        "sms_sim_changed" to "SIM CARD CHANGED!",
        "sms_airplane_on" to "Airplane mode turned ON! Thief cutting communications.",
        "sms_shutdown" to "Phone is SHUTTING DOWN! Last known location below.",
        "sms_reboot" to "Phone is REBOOTING!",
        "sms_silent_on" to "Phone set to SILENT mode!",
        "sms_vibrate" to "Phone set to VIBRATE mode!",
        "sms_charging" to "Phone connected to charger. Battery: %d%%",
        "sms_unplugged" to "Charger disconnected. Battery: %d%%",
        "sms_tamper" to "TAMPER ALERT",
        "sms_theft_activated" to "THEFT MODE ACTIVATED from: %s. All security alerts are now ON.",
        "sms_theft_deactivated" to "Theft mode DEACTIVATED. Back to normal monitoring.",
        "sms_test" to "Thieves Trap is working correctly! All systems OK.",
        "sms_location" to "Location requested.",
        "sms_info" to "Full device information.",
        "sms_ping" to "Auto ping every %d min. Active.",
        "sms_ping_stopped" to "Auto pings stopped.",
        "sms_alarm_on" to "ALARM ACTIVATED! Loud sound playing.",
        "sms_alarm_off" to "Alarm stopped.",
        "sms_locked" to "Phone screen locked.",
        "sms_disarmed_remote" to "Monitoring stopped remotely.",
        "sms_wrong_pin_remote" to "Wrong PIN for remote disarm!",
        "sms_active_already" to "Already active!",
        "sms_location_ping_title" to "AUTO LOCATION PING",
        "sms_new_operator" to "New operator",
        "sms_new_number" to "New number",
        "sms_country" to "Country",
        "sms_iccid" to "New SIM ID",
        "sms_brand" to "Brand",
        "sms_model" to "Model",
        "sms_android" to "Android",
        "sms_android_id" to "Android ID",
        "sms_imei" to "IMEI",
        "sms_owner" to "Owner",
        "sms_operator" to "Operator",
        "sms_network" to "Network",
        "sms_battery" to "Battery",
        "sms_charging_status" to "Charging",
        "sms_not_charging" to "Not charging",
        "sms_location_na" to "Location: GPS acquiring...",
        "sms_accuracy" to "Accuracy",
        "sms_maps" to "Maps",
        "sms_time" to "Time",
        "sms_history_title" to "LOCATION HISTORY",
        "sms_no_history" to "No history yet",
        "sms_selfie_title" to "INTRUDER PHOTO CAPTURED",
        "sms_selfie_body" to "Photo saved. File: %s",
        "sms_premium_required" to "Remote commands require Premium. Upgrade to Full Protection.",
        // Dashboard
        "status_disarmed" to "DISARMED",
        "status_armed" to "ARMED",
        "status_unprotected" to "UNPROTECTED",
        "tap_to_arm" to "Tap ARM to protect this phone",
        "activity_log" to "ACTIVITY LOG",
        "system_idle" to "System idle — no activity yet",
        "stat_alerts" to "Alerts",
        "stat_contact" to "Contact",
        "stat_admin" to "Admin",
        "stat_inactive" to "Inactive",
        "activate_theft" to "ACTIVATE THEFT MODE",
        "sms_credit_warning" to "Ensure your SIM has sufficient credit to send SMS alerts",
        "unlock_full" to "UNLOCK FULL PROTECTION",
        "gallery" to "Gallery",
        "commands" to "Commands",
        // Sidebar
        "nav_settings" to "Settings",
        "nav_premium" to "Full Protection",
        "security_app" to "SECURITY APP",
        "fingerprint_unlock" to "Fingerprint Unlock",
        "change_pin_nav" to "Change PIN",
        "language_nav" to "Language",
        // Settings
        "settings_title" to "Settings",
        "back_btn" to "Back",
        "save_btn" to "Save",
        "telegram_section" to "TELEGRAM ALERTS",
        "how_to_get_id" to "How to get your Chat ID:",
        "telegram_steps" to "1. Tap Open ID Bot below (@User_iinfobot)\n2. Press Start in Telegram\n3. Copy the ID number\n4. Paste it in the field below",
        "paste_chat_id" to "Paste your Chat ID(s) here (comma-separated):",
        "open_id_bot" to "Open ID Bot (@User_iinfobot)",
        "connect_bot" to "Connect Bot",
        "share_bot" to "Share Bot Link",
        "theft_alerts_section" to "THEFT ALERTS",
        "sms_failed_always" to "Always active",
        "alert_after_n" to "Alert after N failed attempts:",
        "grace_section" to "SMART GRACE PERIOD",
        "grace_wrong_pin" to "Wrong PIN detected — wait before alerting",
        "grace_5s" to "5s",
        "grace_60s" to "60s",
        "device_status_section" to "DEVICE STATUS ALERTS — Premium",
        "selfie_sub_tg" to "Photo via Telegram",
        "sim_premium_label" to "Premium",
        "airplane_mode_label" to "Airplane mode",
        "silent_mode_label" to "Silent mode change",
        "remote_section" to "REMOTE CONTROL — Premium",
        "ping_note" to "Note: You can only enable and disable auto location ping remotely. Commands: (PING 2), (PING 5), or (STOP PING).",
        "notifications_section" to "NOTIFICATIONS",
        "notif_status_label" to "Persistent Status Notification",
        "notif_status_sub" to "Show protection status in notification bar",
        "change_pin_btn" to "Change Security PIN",
        // Setup
        "setup_header" to "THIEVES TRAP",
        "setup_subtitle2" to "First Setup — Required before arming",
        "identity_section" to "DEVICE IDENTITY",
        "imei_label2" to "IMEI (Dial *#06# to find)",
        "phone_label" to "Your phone number",
        "pin_section" to "SECURITY PIN",
        "pin_hint_label" to "This PIN is used to disarm the app",
        "contacts_section" to "EMERGENCY CONTACTS",
        "contact1_label" to "Emergency Contact 1 (required)",
        "contact2_label" to "Emergency Contact 2",
        "finish_setup_btn" to "FINISH SETUP",
        // Remote guide
        "remote_title" to "Remote Control Guide",
        "remote_sub" to "Send from ANY phone number — no registration needed",
        "back_arrow" to "Back",
        "how_to_use_title" to "HOW TO USE",
        "how_to_use_body" to "These keywords are your remote commands. Send them from any phone to trigger actions on your device.\n\nOpen SMS app on any phone. Type command (e.g. WHERE). Send to your stolen phone number. The phone responds automatically.",
        "cmd_location_section" to "LOCATION COMMANDS",
        "cmd_device_section" to "DEVICE INFORMATION",
        "cmd_security_section" to "SECURITY ACTIONS",
        "cmd_tracking_section" to "TRACKING",
        "cmd_control_section" to "CONTROL",
        // About
        "about_title" to "About Thieves Trap",
        "about_version_label" to "Version",
        "about_developer" to "Developer",
        "about_copyright" to "Copyright 2026 iLine Tech by Ferak Aladdin",
        // Consent
        "consent_title" to "Privacy Policy & Legal Consent",
        "consent_card1_title" to "Direct Transmission",
        "consent_card1_body" to "Photos and GPS location are sent instantly and exclusively to your private Telegram Bot or SMS contact.",
        "consent_card2_title" to "Absolute Privacy",
        "consent_card2_body" to "We do not own, store, or host any of your personal data on external servers. Your data stays between you and your device.",
        "consent_card3_title" to "Security Permissions",
        "consent_card3_body" to "To detect intruders, the app requires Device Administrator, Camera, and Location access. These are used solely for your protection.",
        "consent_checkbox" to "I have read and agree to the ",
        "consent_privacy_link" to "Privacy Policy",
        "consent_and" to " and ",
        "consent_terms_link" to "Terms of Use.",
        "get_started" to "GET STARTED",
        "sms_help" to "THIEVES TRAP COMMANDS:\nWHERE - GPS location\nINFO - Full device info\nSTATUS - Quick status\nBATTERY - Battery level\nSIM - SIM details\nIMEI - Device IMEI\nHISTORY - Last 5 locations\nALARM - Loud alarm\nSTOP ALARM - Silence alarm\nLOCK - Lock screen\nSELFIE - Take 3 photos\nPING [n] - Auto ping every n min\nSTOP PING - Stop pings\nACTIVE - Activate theft mode\nDEACTIVATE - Deactivate\nDISARM [PIN] - Stop monitoring"
    )

    val FR = mapOf(
        "app_name" to "Piège à Voleurs",
        "arm" to "ARMER",
        "disarm" to "DÉSARMER",
        "armed" to "ARMÉ",
        "disarmed" to "DÉSARMÉ",
        "settings" to "Paramètres",
        "language" to "Langue",
        "last_alert" to "Dernière alerte",
        "never" to "Jamais",
        "not_set" to "Non défini",
        "cancel" to "Annuler",
        "change" to "Modifier",
        "saved" to "Enregistré !",
        "back" to "Retour",
        "enter_pin" to "Entrez votre code PIN",
        "wrong_pin" to "Code PIN incorrect ! Alerte envoyée.",
        "disarm_title" to "Désarmer le Piège à Voleurs",
        "current_pin" to "PIN actuel",
        "new_pin" to "Nouveau PIN (4–6 chiffres)",
        "change_pin" to "Changer le code PIN",
        "pin_too_short" to "Le PIN doit contenir au moins 4 chiffres !",
        "pin_changed" to "PIN modifié avec succès !",
        "setup_title" to "Configuration initiale",
        "setup_subtitle" to "Obligatoire avant armement",
        "setup_done" to "PROTÉGER MON TÉLÉPHONE",
        "setup_complete" to "Configuration terminée ! Téléphone protégé.",
        "imei_required" to "L'IMEI est obligatoire ! Composez *#06# pour le trouver.",
        "contact_required" to "Un numéro de contact d'urgence est requis !",
        "permissions_required" to "Toutes les permissions sont requises !",
        "no_contact" to "Entrez un numéro dans les paramètres d'abord !",
        "admin_explanation" to "Piège à Voleurs a besoin des droits administrateur pour protéger votre téléphone.",
        "mode_theft" to "MODE VOL — toutes les alertes actives",
        "mode_normal" to "Mode normal — surveillance des tentatives",
        "theft_mode_on" to "Mode vol ACTIVÉ",
        "theft_mode_off" to "Mode vol désactivé",
        "premium_required" to "Premium requis",
        "premium_message" to "Cette fonctionnalité est disponible avec la Protection Complète.",
        "upgrade_now" to "Mettre à niveau",
        "not_now" to "Pas maintenant",
        "premium_active" to "Protection Complète Active",
        "free_version" to "Version Gratuite",
        "revoke_license" to "Révoquer la licence",
        "license_revoked" to "Licence révoquée.",
        "license_activated" to "Protection Complète déverrouillée !",
        "license_invalid" to "Clé de licence invalide. Les clés sont spécifiques à l'appareil.",
        "enter_key" to "Entrez la clé de licence",
        "get_device_id" to "Obtenir l'ID de l'appareil",
        "section_identity" to "IDENTITÉ DE L'APPAREIL",
        "section_contacts" to "CONTACTS D'URGENCE",
        "section_theft_alerts" to "ALERTES DE VOL",
        "section_grace" to "DÉLAI DE GRÂCE",
        "section_device_alerts" to "ALERTES D'ÉTAT",
        "section_remote" to "CONTRÔLE À DISTANCE",
        "section_language" to "LANGUE",
        "section_security" to "SÉCURITÉ",
        "section_info" to "INFO APPLICATION",
        "my_number" to "Votre numéro de téléphone",
        "imei_label" to "IMEI (composez *#06#)",
        "imei_hint" to "Ouvrez le composeur et tapez *#06# — votre IMEI apparaît immédiatement.",
        "contact1" to "Contact 1 (obligatoire)",
        "contact2" to "Contact 2",
        "contact2_locked" to "🔒 Contact 2 — Premium uniquement",
        "photo_email" to "Email pour recevoir les photos",
        "photo_email_locked" to "🔒 Email photo — Premium uniquement",
        "save_identity" to "Enregistrer l'identité",
        "save_contacts" to "Enregistrer les contacts",
        "sms_failed_label" to "SMS tentatives échouées",
        "sms_failed_sub" to "Toujours actif",
        "selfie_label" to "Selfie lors des tentatives",
        "selfie_sub" to "Photo enregistrée + envoyée par email (Premium)",
        "sim_change_label" to "SMS changement SIM",
        "sim_change_sub" to "🔒 Premium",
        "grace_toggle_label" to "Activer le délai de grâce",
        "grace_toggle_sub" to "Attendre avant d'envoyer l'alerte",
        "grace_off_label" to "Délai de grâce : DÉSACTIVÉ",
        "airplane_label" to "Mode avion — 🔒 Premium",
        "shutdown_label" to "Extinction / Redémarrage — 🔒 Premium",
        "silent_label" to "Changement mode silencieux — 🔒 Premium",
        "charging_label" to "Connexion/déconnexion chargeur — 🔒 Premium",
        "ping_toggle_label" to "Ping de localisation auto — 🔒 Premium",
        "ping_interval_label" to "Intervalle de ping :",
        "threshold_label" to "Alerter après N tentatives échouées :",
        "change_language" to "Changer la langue",
        "test_sms" to "Envoyer SMS de test",
        "test_sent" to "SMS de test envoyé !",
        "reset_stats" to "Réinitialiser les statistiques",
        "reset_done" to "Statistiques réinitialisées !",
        "total_alerts" to "Total des alertes",
        "revoke_key_btn" to "Révoquer la clé de licence",
        "select_language" to "Choisir la langue",
        "remote_guide_title" to "Guide de contrôle à distance",
        "remote_guide_sub" to "Envoyez depuis N'IMPORTE QUEL téléphone",
        "remote_how_title" to "COMMENT ÇA MARCHE",
        "remote_how_en" to "Ces mots-clés sont vos commandes à distance. Envoyez-les depuis n'importe quel téléphone pour déclencher des actions sur votre appareil volé. Ouvrez les SMS sur un autre téléphone, tapez la commande (ex: WHERE) et envoyez au numéro de votre téléphone volé.",
        "remote_how_ar" to "هذه الكلمات المفتاحية هي اوامر التحكم عن بعد. ارسلها من اي هاتف.",
        "section_location" to "COMMANDES DE LOCALISATION",
        "section_device_info" to "INFORMATIONS APPAREIL",
        "section_security_actions" to "ACTIONS DE SÉCURITÉ",
        "section_tracking" to "SUIVI",
        "section_control" to "CONTRÔLE",
        "sms_armed" to "Piège à Voleurs activé. Téléphone protégé. Envoyez HELP pour les commandes.",
        "sms_unlock" to "Le téléphone a été déverrouillé avec succès !",
        "sms_failed_attempts" to "ATTENTION : %d tentatives de déverrouillage échouées !",
        "sms_sim_changed" to "CARTE SIM CHANGÉE !",
        "sms_airplane_on" to "Mode avion activé ! Le voleur coupe les communications.",
        "sms_shutdown" to "Le téléphone s'ÉTEINT ! Dernière position connue ci-dessous.",
        "sms_reboot" to "Le téléphone REDÉMARRE !",
        "sms_silent_on" to "Téléphone mis en mode SILENCIEUX !",
        "sms_vibrate" to "Téléphone mis en mode VIBRATION !",
        "sms_charging" to "Téléphone branché. Batterie : %d%%",
        "sms_unplugged" to "Chargeur débranché. Batterie : %d%%",
        "sms_tamper" to "ALERTE MANIPULATION",
        "sms_theft_activated" to "MODE VOL ACTIVÉ depuis : %s. Toutes les alertes sont maintenant actives.",
        "sms_theft_deactivated" to "Mode vol DÉSACTIVÉ. Retour à la surveillance normale.",
        "sms_test" to "Piège à Voleurs fonctionne correctement ! Tous les systèmes OK.",
        "sms_location" to "Localisation demandée.",
        "sms_info" to "Informations complètes de l'appareil.",
        "sms_ping" to "Ping automatique toutes les %d min. Actif.",
        "sms_ping_stopped" to "Pings automatiques arrêtés.",
        "sms_alarm_on" to "ALARME ACTIVÉE ! Son fort en cours.",
        "sms_alarm_off" to "Alarme arrêtée.",
        "sms_locked" to "Écran verrouillé.",
        "sms_disarmed_remote" to "Surveillance arrêtée à distance.",
        "sms_wrong_pin_remote" to "Code PIN incorrect pour désarmement !",
        "sms_active_already" to "Déjà actif !",
        "sms_location_ping_title" to "PING DE LOCALISATION AUTO",
        "sms_new_operator" to "Nouvel opérateur",
        "sms_new_number" to "Nouveau numéro",
        "sms_country" to "Pays",
        "sms_iccid" to "Nouvel ID SIM",
        "sms_brand" to "Marque",
        "sms_model" to "Modèle",
        "sms_android" to "Android",
        "sms_android_id" to "ID Android",
        "sms_imei" to "IMEI",
        "sms_owner" to "Propriétaire",
        "sms_operator" to "Opérateur",
        "sms_network" to "Réseau",
        "sms_battery" to "Batterie",
        "sms_charging_status" to "En charge",
        "sms_not_charging" to "Non en charge",
        "sms_location_na" to "Localisation : acquisition GPS...",
        "sms_accuracy" to "Précision",
        "sms_maps" to "Carte",
        "sms_time" to "Heure",
        "sms_history_title" to "HISTORIQUE DES POSITIONS",
        "sms_no_history" to "Pas encore d'historique",
        "sms_selfie_title" to "PHOTO D'INTRUS CAPTURÉE",
        "sms_selfie_body" to "Photo enregistrée. Fichier : %s",
        "sms_premium_required" to "Commandes à distance : Premium requis. Passez à la Protection Complète.",
        // Dashboard
        "status_disarmed" to "DÉSARMÉ",
        "status_armed" to "ARMÉ",
        "status_unprotected" to "NON PROTÉGÉ",
        "tap_to_arm" to "Appuyez sur ARMER pour protéger ce téléphone",
        "activity_log" to "JOURNAL D'ACTIVITÉ",
        "system_idle" to "Système inactif — aucune activité",
        "stat_alerts" to "Alertes",
        "stat_contact" to "Contact",
        "stat_admin" to "Admin",
        "stat_inactive" to "Inactif",
        "activate_theft" to "ACTIVER LE MODE VOL",
        "sms_credit_warning" to "Assurez-vous que votre SIM a assez de crédit pour les SMS",
        "unlock_full" to "OBTENIR LA PROTECTION COMPLÈTE",
        "gallery" to "Galerie",
        "commands" to "Commandes",
        // Sidebar
        "nav_settings" to "Paramètres",
        "nav_premium" to "Protection Complète",
        "security_app" to "APPLICATION SÉCURITÉ",
        "fingerprint_unlock" to "Déverrouillage Empreinte",
        "change_pin_nav" to "Changer le PIN",
        "language_nav" to "Langue",
        // Settings
        "settings_title" to "Paramètres",
        "back_btn" to "Retour",
        "save_btn" to "Enregistrer",
        "telegram_section" to "ALERTES TELEGRAM",
        "how_to_get_id" to "Comment obtenir votre Chat ID :",
        "telegram_steps" to "1. Appuyez sur Ouvrir ID Bot ci-dessous (@User_iinfobot)\n2. Appuyez sur Démarrer dans Telegram\n3. Copiez le numéro ID\n4. Collez-le dans le champ ci-dessous",
        "paste_chat_id" to "Collez votre Chat ID(s) ici (séparés par virgule) :",
        "open_id_bot" to "Ouvrir ID Bot (@User_iinfobot)",
        "connect_bot" to "Connecter le Bot",
        "share_bot" to "Partager le lien Bot",
        "theft_alerts_section" to "ALERTES DE VOL",
        "sms_failed_always" to "Toujours actif",
        "alert_after_n" to "Alerter après N tentatives échouées :",
        "grace_section" to "DÉLAI DE GRÂCE INTELLIGENT",
        "grace_wrong_pin" to "PIN incorrect détecté — attendre avant d'alerter",
        "grace_5s" to "5s",
        "grace_60s" to "60s",
        "device_status_section" to "ALERTES D'ÉTAT — Premium",
        "selfie_sub_tg" to "Photo via Telegram",
        "sim_premium_label" to "Premium",
        "airplane_mode_label" to "Mode avion",
        "silent_mode_label" to "Changement mode silencieux",
        "remote_section" to "CONTRÔLE À DISTANCE — Premium",
        "ping_note" to "Note : Vous pouvez uniquement activer/désactiver le ping de localisation à distance. Commandes : (PING 2), (PING 5), ou (STOP PING).",
        "notifications_section" to "NOTIFICATIONS",
        "notif_status_label" to "Notification de statut persistante",
        "notif_status_sub" to "Afficher le statut de protection dans la barre",
        "change_pin_btn" to "Changer le code PIN",
        // Setup
        "setup_header" to "THIEVES TRAP",
        "setup_subtitle2" to "Configuration initiale — Requis avant armement",
        "identity_section" to "IDENTITÉ DE L'APPAREIL",
        "imei_label2" to "IMEI (Composez *#06# pour trouver)",
        "phone_label" to "Votre numéro de téléphone",
        "pin_section" to "CODE PIN DE SÉCURITÉ",
        "pin_hint_label" to "Ce PIN est utilisé pour désarmer l'application",
        "contacts_section" to "CONTACTS D'URGENCE",
        "contact1_label" to "Contact d'urgence 1 (obligatoire)",
        "contact2_label" to "Contact d'urgence 2",
        "finish_setup_btn" to "TERMINER LA CONFIGURATION",
        // Remote guide
        "remote_title" to "Guide de contrôle à distance",
        "remote_sub" to "Envoyez depuis N'IMPORTE QUEL numéro — sans inscription",
        "back_arrow" to "Retour",
        "how_to_use_title" to "COMMENT UTILISER",
        "how_to_use_body" to "Ces mots-clés sont vos commandes à distance. Envoyez-les depuis n'importe quel téléphone pour déclencher des actions sur votre appareil.\n\nOuvrez l'app SMS. Tapez la commande (ex: WHERE). Envoyez au numéro de votre téléphone volé. Le téléphone répond automatiquement.",
        "cmd_location_section" to "COMMANDES DE LOCALISATION",
        "cmd_device_section" to "INFORMATIONS APPAREIL",
        "cmd_security_section" to "ACTIONS DE SÉCURITÉ",
        "cmd_tracking_section" to "SUIVI",
        "cmd_control_section" to "CONTRÔLE",
        // About
        "about_title" to "À propos de Piège à Voleurs",
        "about_version_label" to "Version",
        "about_developer" to "Développeur",
        "about_copyright" to "Copyright 2026 iLine Tech par Ferak Aladdin",
        // Consent
        "consent_title" to "Politique de confidentialité et consentement",
        "consent_card1_title" to "Transmission directe",
        "consent_card1_body" to "Les photos et la localisation GPS sont envoyées instantanément et exclusivement à votre bot Telegram privé ou contact SMS.",
        "consent_card2_title" to "Confidentialité absolue",
        "consent_card2_body" to "Nous ne possédons, stockons ni hébergeons aucune de vos données personnelles sur des serveurs externes.",
        "consent_card3_title" to "Permissions de sécurité",
        "consent_card3_body" to "Pour détecter les intrus, l'application nécessite l'accès Administrateur, Caméra et Localisation.",
        "consent_checkbox" to "J'ai lu et j'accepte la ",
        "consent_privacy_link" to "Politique de confidentialité",
        "consent_and" to " et les ",
        "consent_terms_link" to "Conditions d'utilisation.",
        "get_started" to "COMMENCER",
        "sms_help" to "COMMANDES PIÈGE À VOLEURS :\nWHERE - Position GPS\nINFO - Infos complètes\nSTATUS - Statut rapide\nBATTERY - Batterie\nSIM - Détails SIM\nIMEI - IMEI appareil\nHISTORY - 5 dernières positions\nALARM - Alarme forte\nSTOP ALARM - Arrêter alarme\nLOCK - Verrouiller écran\nSELFIE - 3 photos\nPING [n] - Ping auto\nSTOP PING - Arrêter pings\nACTIVE - Activer mode vol\nDEACTIVATE - Désactiver\nDISARM [PIN] - Arrêter surveillance"
    )

    val AR = mapOf(
        "app_name" to "فخ اللصوص",
        "arm" to "تفعيل الحماية",
        "disarm" to "إيقاف الحماية",
        "armed" to "الحماية مفعّلة",
        "disarmed" to "الحماية موقوفة",
        "settings" to "الإعدادات",
        "language" to "اللغة",
        "last_alert" to "آخر تنبيه",
        "never" to "أبداً",
        "not_set" to "غير محدد",
        "cancel" to "إلغاء",
        "change" to "تغيير",
        "saved" to "تم الحفظ!",
        "back" to "رجوع",
        "enter_pin" to "أدخل رمز PIN",
        "wrong_pin" to "رمز PIN خاطئ! تم إرسال تنبيه.",
        "disarm_title" to "إيقاف فخ اللصوص",
        "current_pin" to "PIN الحالي",
        "new_pin" to "PIN جديد (4–6 أرقام)",
        "change_pin" to "تغيير رمز PIN",
        "pin_too_short" to "يجب أن يكون PIN 4 أرقام على الأقل!",
        "pin_changed" to "تم تغيير PIN بنجاح!",
        "setup_title" to "الإعداد الأولي",
        "setup_subtitle" to "مطلوب قبل التفعيل",
        "setup_done" to "ابدأ حماية هاتفي",
        "setup_complete" to "اكتمل الإعداد! الهاتف محمي الآن.",
        "imei_required" to "رقم IMEI مطلوب! اتصل بـ *#06# للعثور عليه.",
        "contact_required" to "رقم جهة الاتصال الطارئة مطلوب!",
        "permissions_required" to "جميع الأذونات مطلوبة!",
        "no_contact" to "أدخل رقم هاتف في الإعدادات أولاً!",
        "admin_explanation" to "فخ اللصوص يحتاج صلاحيات المشرف لحماية هاتفك.",
        "mode_theft" to "وضع السرقة — جميع التنبيهات مفعّلة",
        "mode_normal" to "الوضع العادي — مراقبة محاولات كلمة المرور",
        "theft_mode_on" to "تم تفعيل وضع السرقة",
        "theft_mode_off" to "تم إلغاء وضع السرقة",
        "premium_required" to "مطلوب الاشتراك المدفوع",
        "premium_message" to "هذه الميزة متاحة في خطة الحماية الكاملة.",
        "upgrade_now" to "الترقية الآن",
        "not_now" to "ليس الآن",
        "premium_active" to "الحماية الكاملة مفعّلة",
        "free_version" to "النسخة المجانية",
        "revoke_license" to "إلغاء الترخيص",
        "license_revoked" to "تم إلغاء الترخيص.",
        "license_activated" to "تم تفعيل الحماية الكاملة!",
        "license_invalid" to "مفتاح الترخيص غير صالح. المفاتيح خاصة بالجهاز.",
        "enter_key" to "أدخل مفتاح الترخيص",
        "get_device_id" to "الحصول على معرّف الجهاز",
        "section_identity" to "هوية الجهاز",
        "section_contacts" to "جهات الاتصال الطارئة",
        "section_theft_alerts" to "تنبيهات السرقة",
        "section_grace" to "فترة السماح الذكية",
        "section_device_alerts" to "تنبيهات حالة الجهاز",
        "section_remote" to "التحكم عن بُعد",
        "section_language" to "اللغة",
        "section_security" to "الأمان",
        "section_info" to "معلومات التطبيق",
        "my_number" to "رقم هاتفك",
        "imei_label" to "IMEI (اتصل بـ *#06#)",
        "imei_hint" to "افتح الهاتف واتصل بـ *#06# — سيظهر رقم IMEI فوراً.",
        "contact1" to "جهة الاتصال 1 (مطلوب)",
        "contact2" to "جهة الاتصال 2",
        "contact2_locked" to "🔒 جهة الاتصال 2 — للمدفوعين فقط",
        "photo_email" to "البريد الإلكتروني لاستقبال الصور",
        "photo_email_locked" to "🔒 بريد الصور — للمدفوعين فقط",
        "save_identity" to "حفظ الهوية",
        "save_contacts" to "حفظ جهات الاتصال",
        "sms_failed_label" to "رسالة عند فشل الإدخال",
        "sms_failed_sub" to "دائماً مفعّل",
        "selfie_label" to "صورة عند فشل الإدخال",
        "selfie_sub" to "الصورة محفوظة + إرسال بالبريد (مدفوع)",
        "sim_change_label" to "رسالة عند تغيير SIM",
        "sim_change_sub" to "🔒 للمدفوعين",
        "grace_toggle_label" to "تفعيل فترة السماح",
        "grace_toggle_sub" to "انتظر قبل إرسال التنبيه بعد كلمة مرور خاطئة",
        "grace_off_label" to "فترة السماح: غير مفعّلة",
        "airplane_label" to "وضع الطيران — 🔒 للمدفوعين",
        "shutdown_label" to "الإغلاق / إعادة التشغيل — 🔒 للمدفوعين",
        "silent_label" to "تغيير وضع الصوت — 🔒 للمدفوعين",
        "charging_label" to "توصيل/فصل الشاحن — 🔒 للمدفوعين",
        "ping_toggle_label" to "الموقع التلقائي — 🔒 للمدفوعين",
        "ping_interval_label" to "فترة الإرسال:",
        "threshold_label" to "التنبيه بعد N محاولة فاشلة:",
        "change_language" to "تغيير اللغة",
        "test_sms" to "إرسال رسالة اختبار",
        "test_sent" to "تم إرسال رسالة الاختبار!",
        "reset_stats" to "إعادة تعيين الإحصائيات",
        "reset_done" to "تم إعادة تعيين الإحصائيات!",
        "total_alerts" to "إجمالي التنبيهات",
        "revoke_key_btn" to "إلغاء مفتاح الترخيص",
        "select_language" to "اختر اللغة",
        "remote_guide_title" to "دليل التحكم عن بُعد",
        "remote_guide_sub" to "أرسل من أي هاتف — بدون تسجيل",
        "remote_how_title" to "كيف يعمل",
        "remote_how_en" to "These keywords are your remote commands. Send them from any phone to trigger actions on your stolen device.",
        "remote_how_ar" to "هذه الكلمات المفتاحية هي اوامر التحكم عن بعد. ارسلها من اي هاتف محمول آخر الى هاتفك المسروق لتفعيل الحماية. افتح الرسائل على اي هاتف، اكتب الامر (مثل WHERE) وارسله الى رقم هاتفك المسروق.",
        "section_location" to "أوامر الموقع",
        "section_device_info" to "معلومات الجهاز",
        "section_security_actions" to "إجراءات الأمان",
        "section_tracking" to "التتبع",
        "section_control" to "التحكم",
        "sms_armed" to "تم تفعيل فخ اللصوص. الهاتف محمي. أرسل HELP للأوامر.",
        "sms_unlock" to "تم فتح قفل الهاتف بنجاح!",
        "sms_failed_attempts" to "تحذير: %d محاولات فاشلة لفتح القفل!",
        "sms_sim_changed" to "تم تغيير شريحة SIM!",
        "sms_airplane_on" to "تم تفعيل وضع الطيران! اللص يقطع الاتصالات.",
        "sms_shutdown" to "الهاتف يُغلق! آخر موقع معروف أدناه.",
        "sms_reboot" to "الهاتف يُعيد التشغيل!",
        "sms_silent_on" to "تم تفعيل الوضع الصامت!",
        "sms_vibrate" to "تم تفعيل وضع الاهتزاز!",
        "sms_charging" to "الهاتف متصل بالشاحن. البطارية: %d%%",
        "sms_unplugged" to "تم فصل الشاحن. البطارية: %d%%",
        "sms_tamper" to "تنبيه تلاعب",
        "sms_theft_activated" to "تم تفعيل وضع السرقة من: %s. جميع تنبيهات الأمان مفعّلة الآن.",
        "sms_theft_deactivated" to "تم إلغاء وضع السرقة. العودة للمراقبة العادية.",
        "sms_test" to "فخ اللصوص يعمل بشكل صحيح! جميع الأنظمة OK.",
        "sms_location" to "تم طلب الموقع.",
        "sms_info" to "معلومات كاملة عن الجهاز.",
        "sms_ping" to "إرسال الموقع تلقائياً كل %d دقيقة. مفعّل.",
        "sms_ping_stopped" to "تم إيقاف الإرسال التلقائي.",
        "sms_alarm_on" to "تم تفعيل الإنذار! صوت عالٍ يعمل.",
        "sms_alarm_off" to "تم إيقاف الإنذار.",
        "sms_locked" to "تم قفل شاشة الهاتف.",
        "sms_disarmed_remote" to "تم إيقاف المراقبة عن بُعد.",
        "sms_wrong_pin_remote" to "رمز PIN خاطئ للإيقاف عن بُعد!",
        "sms_active_already" to "مفعّل مسبقاً!",
        "sms_location_ping_title" to "إرسال الموقع التلقائي",
        "sms_new_operator" to "المشغل الجديد",
        "sms_new_number" to "الرقم الجديد",
        "sms_country" to "الدولة",
        "sms_iccid" to "معرف SIM الجديد",
        "sms_brand" to "الماركة",
        "sms_model" to "الموديل",
        "sms_android" to "أندرويد",
        "sms_android_id" to "معرف أندرويد",
        "sms_imei" to "IMEI",
        "sms_owner" to "المالك",
        "sms_operator" to "المشغل",
        "sms_network" to "الشبكة",
        "sms_battery" to "البطارية",
        "sms_charging_status" to "يشحن",
        "sms_not_charging" to "لا يشحن",
        "sms_location_na" to "الموقع: جارٍ تحديد GPS...",
        "sms_accuracy" to "الدقة",
        "sms_maps" to "الخريطة",
        "sms_time" to "الوقت",
        "sms_history_title" to "سجل المواقع",
        "sms_no_history" to "لا يوجد سجل بعد",
        "sms_selfie_title" to "تم التقاط صورة للمتسلل",
        "sms_selfie_body" to "الصورة محفوظة. الملف: %s",
        "sms_premium_required" to "الأوامر عن بُعد تتطلب الاشتراك المدفوع. قم بالترقية.",
        // Dashboard
        "status_disarmed" to "الحماية موقوفة",
        "status_armed" to "الحماية مفعّلة",
        "status_unprotected" to "غير محمي",
        "tap_to_arm" to "اضغط تفعيل لحماية هذا الهاتف",
        "activity_log" to "سجل النشاط",
        "system_idle" to "النظام خامل — لا نشاط بعد",
        "stat_alerts" to "تنبيهات",
        "stat_contact" to "جهة الاتصال",
        "stat_admin" to "المشرف",
        "stat_inactive" to "غير نشط",
        "activate_theft" to "تفعيل وضع السرقة",
        "sms_credit_warning" to "تأكد من وجود رصيد كافٍ في شريحة SIM لإرسال رسائل التنبيه",
        "unlock_full" to "الحصول على الحماية الكاملة",
        "gallery" to "المعرض",
        "commands" to "الأوامر",
        // Sidebar
        "nav_settings" to "الإعدادات",
        "nav_premium" to "الحماية الكاملة",
        "security_app" to "تطبيق الأمان",
        "fingerprint_unlock" to "فتح القفل بالبصمة",
        "change_pin_nav" to "تغيير PIN",
        "language_nav" to "اللغة",
        // Settings
        "settings_title" to "الإعدادات",
        "back_btn" to "رجوع",
        "save_btn" to "حفظ",
        "telegram_section" to "تنبيهات تيليغرام",
        "how_to_get_id" to "كيفية الحصول على Chat ID:",
        "telegram_steps" to "1. اضغط على 'فتح بوت ID' أدناه (@User_iinfobot)\n2. اضغط Start في تيليغرام\n3. انسخ رقم ID\n4. الصقه في الحقل أدناه",
        "paste_chat_id" to "الصق Chat ID(s) هنا (مفصولة بفاصلة):",
        "open_id_bot" to "فتح بوت ID (@User_iinfobot)",
        "connect_bot" to "ربط البوت",
        "share_bot" to "مشاركة رابط البوت",
        "theft_alerts_section" to "تنبيهات السرقة",
        "sms_failed_always" to "دائماً مفعّل",
        "alert_after_n" to "التنبيه بعد N محاولة فاشلة:",
        "grace_section" to "فترة السماح الذكية",
        "grace_wrong_pin" to "PIN خاطئ — انتظر قبل إرسال التنبيه",
        "grace_5s" to "٥ث",
        "grace_60s" to "٦٠ث",
        "device_status_section" to "تنبيهات حالة الجهاز — مدفوع",
        "selfie_sub_tg" to "صورة عبر تيليغرام",
        "sim_premium_label" to "للمدفوعين",
        "airplane_mode_label" to "وضع الطيران",
        "silent_mode_label" to "تغيير الوضع الصامت",
        "remote_section" to "التحكم عن بُعد — مدفوع",
        "ping_note" to "ملاحظة: يمكنك فقط تفعيل/إيقاف إرسال الموقع التلقائي عن بُعد. الأوامر: (PING 2)، (PING 5)، أو (STOP PING).",
        "notifications_section" to "الإشعارات",
        "notif_status_label" to "إشعار الحالة الدائم",
        "notif_status_sub" to "عرض حالة الحماية في شريط الإشعارات",
        "change_pin_btn" to "تغيير رمز PIN",
        // Setup
        "setup_header" to "THIEVES TRAP",
        "setup_subtitle2" to "الإعداد الأولي — مطلوب قبل التفعيل",
        "identity_section" to "هوية الجهاز",
        "imei_label2" to "IMEI (اتصل بـ *#06# للعثور عليه)",
        "phone_label" to "رقم هاتفك",
        "pin_section" to "رمز PIN للأمان",
        "pin_hint_label" to "يُستخدم هذا الرمز لإيقاف التطبيق",
        "contacts_section" to "جهات الاتصال الطارئة",
        "contact1_label" to "جهة الاتصال الطارئة 1 (مطلوب)",
        "contact2_label" to "جهة الاتصال الطارئة 2",
        "finish_setup_btn" to "إنهاء الإعداد",
        // Remote guide
        "remote_title" to "دليل التحكم عن بُعد",
        "remote_sub" to "أرسل من أي رقم هاتف — بدون تسجيل",
        "back_arrow" to "رجوع",
        "how_to_use_title" to "طريقة الاستخدام",
        "how_to_use_body" to "هذه الكلمات المفتاحية هي أوامر التحكم عن بُعد. أرسلها من أي هاتف لتفعيل الإجراءات على جهازك.\n\nافتح تطبيق الرسائل. اكتب الأمر (مثل WHERE). أرسله إلى رقم هاتفك المسروق. الهاتف يرد تلقائياً.",
        "cmd_location_section" to "أوامر الموقع",
        "cmd_device_section" to "معلومات الجهاز",
        "cmd_security_section" to "إجراءات الأمان",
        "cmd_tracking_section" to "التتبع",
        "cmd_control_section" to "التحكم",
        // About
        "about_title" to "حول فخ اللصوص",
        "about_version_label" to "الإصدار",
        "about_developer" to "المطوّر",
        "about_copyright" to "حقوق النشر 2026 iLine Tech بواسطة فراق علاء الدين",
        // Consent
        "consent_title" to "سياسة الخصوصية والموافقة القانونية",
        "consent_card1_title" to "إرسال مباشر",
        "consent_card1_body" to "تُرسل الصور وموقع GPS فوراً وحصرياً إلى بوت تيليغرام الخاص بك أو جهة الاتصال عبر SMS.",
        "consent_card2_title" to "خصوصية مطلقة",
        "consent_card2_body" to "لا نمتلك أو نخزن أو نستضيف أياً من بياناتك الشخصية على خوادم خارجية. بياناتك تبقى بينك وبين جهازك.",
        "consent_card3_title" to "أذونات الأمان",
        "consent_card3_body" to "للكشف عن المتسللين، يحتاج التطبيق إلى صلاحيات مشرف الجهاز والكاميرا والموقع. تُستخدم هذه فقط لحمايتك.",
        "consent_checkbox" to "لقد قرأت وأوافق على ",
        "consent_privacy_link" to "سياسة الخصوصية",
        "consent_and" to " و",
        "consent_terms_link" to "شروط الاستخدام.",
        "get_started" to "ابدأ الآن",
        "sms_help" to "أوامر فخ اللصوص:\nWHERE - الموقع\nINFO - معلومات كاملة\nSTATUS - حالة سريعة\nBATTERY - البطارية\nSIM - تفاصيل SIM\nIMEI - رقم IMEI\nHISTORY - آخر 5 مواقع\nALARM - إنذار صوتي\nSTOP ALARM - إيقاف الإنذار\nLOCK - قفل الشاشة\nSELFIE - 3 صور\nPING [n] - إرسال تلقائي\nSTOP PING - إيقاف\nACTIVE - تفعيل وضع السرقة\nDEACTIVATE - إلغاء التفعيل\nDISARM [PIN] - إيقاف المراقبة"
    )
}
